version: "3.8"
services:
  app:
    build: .
    ports:
      - "7080:7080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5433/todo_db
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: type-orm-db
    image: postgres:12.9
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
